---
fail_fast: true
minimum_pre_commit_version: "2.6.0"
repos:
###### PLACEHOLDER FOR TERRAFORM LINTING ######
## Terraform Linting
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 521ada54e82bdee23c6a1f42a83cd22898f1efd4 #v1.99.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=--recursive
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.config/tf-lint/.tflint.hcl
###############################################

###### PLACEHOLDER FOR CFN LINTING       ######
## CloudFormation Linting
- repo: https://github.com/aws-cloudformation/cfn-lint
  rev: v1.34.2 # The version of cfn-lint to use
  hooks:
    - id: cfn-lint
      files: cloudformation/.*\.(json|yml|yaml)$
###############################################

###### PLACEHOLDER FOR CHECKOV CHECKS    ######
## Checkov checks
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 112ff682598c6a7121665f38eee31c872df66bf2 # v3.2.408
  hooks:
    - id: checkov
      entry: checkov -d . --config-file .config/checkov/.checkov.yaml --framework terraform,cloudformation
    - id: checkov_secrets
###############################################

###### PLACEHOLDER FOR CFN GUARD CHECKS  ######
## CFN Guard checks
- repo: https://github.com/aws-cloudformation/cloudformation-guard
  rev: 93348197f08c2b5ab1e0fb31a31833285d2d4fe3 # pre-commit v0.0.2
  hooks:
    - id: cfn-guard
      args:
        - --operation=validate # Specify the validate operation
        - --rules=.config/cfn-guard/ # Rules directory
      files: cloudformation/.* # Directory to watch for changes and validate against
###############################################

## General linting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b #v5.0.0
  hooks:
  - id: trailing-whitespace
